spring:
    application:
        name: customers
    sleuth:
      sampler:
        probability: 1.0
    zipkin:
      base-url: http://172.18.0.9:9411

logging.level.org.springframework.cloud.sleuth: DEBUG