version: '3'
services:
  book1:
    build:
      context: ./books
      dockerfile: Dockerfile
    image: books
    ports:
      - 8082:8080
  book2:
    build:
      context: ./books
      dockerfile: Dockerfile
    image: books
    ports:
      - 8081:8080
  customer:
    build:
      context: ./customers
      dockerfile: Dockerfile
    image: customers
    ports:
      - 8083:8080

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    image: gateway
    ports:
      - 8084:8080