version: '3'
networks:
  cluster:
    driver: bridge

services:
  zipking-server:
    build:
      context: ./zipkin-server
      dockerfile: Dockerfile
    image: zipkin-server
    ports:
      - 9411:9411
    networks:
      cluster:
        ipv4_address: 172.18.0.9
        aliases:
          - zipkin-server

  book1:
    build:
      args:
        REGISTER_AS: http://172.18.0.2:8080
      context: ./books
      dockerfile: Dockerfile
    image: books
    ports:
      - 8082:8080
    networks:
      cluster:
        ipv4_address: 172.18.0.2
        aliases:
          - book1

  book2:
    build:
      args:
        REGISTER_AS: http://172.18.0.3:8080
      context: ./books
      dockerfile: Dockerfile
    image: books
    ports:
      - 8081:8080
    networks:
      cluster:
        ipv4_address: 172.18.0.3
        aliases:
          - book2
  customer:
    build:
      args:
        REGISTER_AS: http://172.18.0.4:8080
      context: ./customers
      dockerfile: Dockerfile
    image: customers
    ports:
      - 8083:8080
    networks:
      cluster:
        ipv4_address: 172.18.0.4
        aliases:
          - customers

  gateway:
    build:
      args:
        REGISTER_AS: http://172.18.0.5:8080
      context: ./gateway
      dockerfile: Dockerfile
    image: gateway
    ports:
      - 8084:8080
    networks:
      cluster:
        ipv4_address: 172.18.0.5

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    image: admin
    ports:
      - 8088:8080
    networks:
      cluster:
        ipv4_address: 172.18.0.8