version: '3'
networks:
  cluster:
    driver: bridge

services:
  book1:
    build:
      context: ./books
      dockerfile: Dockerfile
    image: books
    hostname: book1
    ports:
      - 8082:8080
    networks:
      cluster:
        ipv4_address: 172.18.0.2
        aliases:
          - book1

  book2:
    build:
      context: ./books
      dockerfile: Dockerfile
    image: books
    hostname: book2
    ports:
      - 8081:8080
    networks:
      cluster:
        ipv4_address: 172.18.0.3
        aliases:
          - book2
  customer:
    build:
      context: ./customers
      dockerfile: Dockerfile
    image: customers
    hostname: customers
    ports:
      - 8083:8080
    networks:
      cluster:
        ipv4_address: 172.18.0.4
        aliases:
          - customers

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    image: gateway
    ports:
      - 8084:8080
    networks:
      cluster:
        ipv4_address: 172.18.0.5