spring:
    application:
        name: gateway
book-service:
    ribbon:
        eureka:
            enabled: false
        listOfServers: localhost:8081, localhost:8082
        ServerListRefreshInterval: 15000
