spring:
  application:
      name: cutomer-library
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    discoveryClientEnabled: true
    base-url: http://zipkin-service/

logging.level.org.springframework.cloud.sleuth: DEBUG

eureka:
  client:
    enabled: false

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

sample:
  zipkin:
    enabled: true

book-service:
  ribbon:
    eureka:
        enabled: false
    listOfServers: localhost:8081, localhost:8082
    ServerListRefreshInterval: 15000

zipkin-service:
  ribbon:
    eureka:
        enabled: false
    listOfServers: localhost:9411
    ServerListRefreshInterval: 15000

clients-service:
  ribbon:
    eureka:
        enabled: false
    listOfServers: http://localhost:8083
    ServerListRefreshInterval: 15000