spring:
  application:
      name: cutomer-library
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    discoveryClientEnabled: true
    base-url: http://zipkin-service/

logging:
  file: logs/dev_app.log
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %X{mdcData} - [%X{X-B3-TraceId:-}] - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %X{mdcData} - [%X{X-B3-TraceId:-}] - %msg%n"

eureka:
  client:
    enabled: false

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

sample:
  zipkin:
    enabled: true

book-service:
  ribbon:
    eureka:
        enabled: false
    listOfServers: http://172.18.0.2:8080, http://172.18.0.3:8080
    ServerListRefreshInterval: 15000

zipkin-service:
  ribbon:
    eureka:
        enabled: false
    listOfServers: http://172.18.0.9:9411
    ServerListRefreshInterval: 15000

clients-service:
  ribbon:
    eureka:
        enabled: false
    listOfServers: http://172.18.0.4:8080
    ServerListRefreshInterval: 15000