spring:
  application:
    name: books-service
  sleuth.sampler.probability: 1.0
  zipkin:
    base-url: http://172.18.0.9:9411
logging:
  file: logs/dev_app.log
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %X{mdcData} - [%X{X-B3-TraceId:-}] - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %X{mdcData} - [%X{X-B3-TraceId:-}] - %msg%n"